name: supabase_flutter
description: Flutter integration for Supabase. This package makes it simple for developers to build secure and scalable products.
version: 1.0.0-dev.4
homepage: 'https://supabase.io'
repository: 'https://github.com/supabase/supabase-flutter'

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  app_links: ^3.2.0
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  supabase: ^1.0.0-dev.4
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
